### ISSUE TITLE
SpringBoot Tutorial

### ISSUE THREAD

**Issue by DanielAB95** [Arquisoft/wiq_es04b#108]
Help with spring boot

**Comment by RicardoDiNu** [comment]
Tutorial completed, but there was a question that I could not solve, @DanielAB95 cannot execute the runServer.bat file to start the database, I think it may be due to a problem with the installed java version and the environment variables, does anyone have any ideas?

**Comment by Pelayori** [comment]
Do you have a `lib` folder inside `database/hsqldb` folder ?

**Comment by DanielAB95** [comment]
I have this
![imagen_2024-03-04_195111279](https://github.com/Arquisoft/wiq_es04b/assets/158168058/c2aa7759-0508-4caf-8cc5-25a2a7d0fc89)

**Comment by Pelayori** [comment]
Can you post a picture of the error you get?

**Comment by DanielAB95** [comment]
It just does not open when you execute it. I mean, it open the cmd but it get close inmediately

**Comment by RicardoDiNu** [comment]
If a .bat file opens a Command Prompt window and then closes immediately without giving you a chance to see what's happening, it's likely that the script contained within the .bat file is executing too quickly and then exiting. This can happen if the commands within the .bat file are not properly structured.

Here are a few steps you can take to troubleshoot and potentially fix the issue:

Open Command Prompt Manually: Try running the .bat file manually by opening Command Prompt first, then navigating to the directory where the .bat file is located, and finally executing the .bat file. This way, you'll be able to see any error messages that are displayed before the window closes.

Add Pause Command: Add a pause command at the end of your .bat file. This will cause the Command Prompt window to remain open after executing the commands, allowing you to see any error messages. Simply add a new line at the end of your .bat file with the word pause.

Check for Errors: Review the commands in your .bat file to ensure they are correct. Pay attention to any commands that might be causing the window to close prematurely.

Redirect Output: You can redirect the output of your .bat file to a text file by adding > output.txt at the end of the command line in your .bat file. This will capture any output or error messages that occur during execution.

Run with Administrator Privileges: If your .bat file requires administrative privileges, try running Command Prompt as an administrator and then executing the .bat file from there.

By following these steps, you should be able to diagnose and fix the issue with your .bat file.
