### ISSUE TITLE
Overlapping on a branch

### ISSUE THREAD

**Issue by uo288061** [Arquisoft/wiq_es04b#121]
For the rankings, Ricardo and I have been working in the same branch. Before either of us pushed changes, we compared our implementations, and we decided to push Ricardo's version because his code is clearer. However, since we are on the same branch, if I push my local changes, it would alter some of the things Ricardo did, and I don't want that. I simply want to showcase the work I've done, even if it won't be used in the project. In summary, how do I push my changes without modifying what Ricardo has done (we are on the same branch)?

**Comment by RicardoDiNu** [comment]
We have already solved the problem
