### ISSUE TITLE
Italic Text in Glossary

### ISSUE THREAD

**Issue by uo288061** [Arquisoft/wiq_es04b#44]
The glossary appears in italics without apparent reason. To italicize text, it should be placed between underscores; however, even without being between underscores, the <em> tag appears in index.html.
If someone knows how to fix it, please let me know.

**Comment by uo287545** [comment]
Already fixed. You shouldn't use the variable cols="e,2e" when creating a table in ASCIIDOC as it appears to italice the whole table.
