### ISSUE TITLE
No funciona el npm install

### ISSUE THREAD

**Issue by DanielAB95** [Arquisoft/wiq_es04b#8]
En la terminal al ejecutar en "npm install" sale el error "El término 'npm' no se reconoce como nombre de un cmdlet, funcion, archivo de scipt o programa ejecutable.

**Comment by Pelayori** [comment]
Para arreglar este error se debe instalar Node JS desde la página oficial de node 
https://nodejs.org/en/download/current

Recomendable instalar la versión LTS.

**Comment by Pelayori** [comment]
Entiendo que se ha solucionado al no haber respuesta.
